// <auto-generated />
using System;
using KEOPBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KEOPBackend.Migrations.SpentAnalysisDb
{
    [DbContext(typeof(SpentAnalysisDbContext))]
    [Migration("20240206100736_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KEOPBackend.Models.SpentAnalysis", b =>
                {
                    b.Property<int>("spent_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("spent_id"));

                    b.Property<DateTime?>("created_on")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("modified_on")
                        .HasColumnType("datetime2");

                    b.Property<string>("spent_data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("spent_id");

                    b.ToTable("SpentAnalyses");
                });
#pragma warning restore 612, 618
        }
    }
}
